# Existing mkdocs.yml content
site_name: Open beleidsontwikkeling
site_description: Open beleid van het Ministerie van Volksgezondheid, Welzijn en Sport

theme: 
    name: material
    custom_dir: src/overrides
    language: nl
    palette:
        primary: custom
    logo: assets/img/logo.svg
    favicon: assets/img/favicon.ico
    font: false 
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - navigation.instant
        - navigation.footer
        - navigation.prune
        - navigation.path
        - search.highlight
        # - search.suggest
        - content.tooltips
        - content.tabs.link
    icon:
        logo: fontawesome/solid/house
        annotation: fontawesome/solid/circle-info

nav:
    - 'Open beleidsontwikkeling' : "index.md"

# Extra opties
markdown_extensions:
    - md_in_html
    - toc:
        toc_depth: 2
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Extra opties voor footer
extra: 
    social:
        - icon: fontawesome/brands/github 
          link: https://github.com/minvws/beleidsontwikkeling

extra_css:
  # - stylesheets/admonition.css
  - stylesheets/colorblocks.css
  - stylesheets/navigation.css
  - stylesheets/extra.css
  - stylesheets/footer.css

plugins:
    # - glightbox
    - search
    - git-revision-date-localized:
        timezone: Europe/Amsterdam
        locale: nl
        exclude:
          - index.md
    - awesome-pages:
        collapse_single_pages: true
    - redirects:
        redirect_maps:
            'ambitieladder.md': 'open-source-ambitieladder-voor-maatwerk-aanbesteding-of-opdracht.md'

hooks:
    - src/overrides/hooks/includes.py
    - src/overrides/hooks/admonition.py
    - src/overrides/hooks/colorblocks.py
    - src/overrides/hooks/newlines.py
    - src/overrides/hooks/escapes.py
    - src/overrides/hooks/title.py
    - src/overrides/hooks/demote-headers.py

# Link naar GitHub repo
repo_url: https://github.com/minvws/beleidsontwikkeling
site_url: https://minvws.github.io/beleidsontwikkeling/
edit_uri: edit/main/docs/