name: Generate pdf's and deploy mkdocs site to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Amsterdam"

      - run: src/scripts/includes.sh
      - run: docker pull pandoc/extra:3.7.0.2
      - run: mkdir /tmp/fonts && tar -zxvf docs/assets/fonts/cantarell.tar.gz -C /tmp/fonts && tar -zxvf docs/assets/fonts/noto-emoji.tar.gz -C /tmp/fonts
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: src/scripts/convert.sh

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: docs/**/*.pdf

  mkdocs:
    runs-on: ubuntu-latest
    needs: pandoc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Amsterdam"

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          name: pdfs
          path: docs/

      - run: mkdocs build -d _site

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: mkdocs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4